### ISSUE TITLE
Choose a license for the code

### ISSUE THREAD

**Issue by Dhole** [Kuska-ssb/kuska-handshake#14]

**Comment by adria0** [comment]
@Dhole, GPLv3? Others?

**Comment by Dhole** [comment]
For reference:
- The standard js implementation is published under MIT license.
- Rust is published under both the MIT license and the Apache License (Version 2.0).

Also, apart from GPLv3 there's LGPLv3.  One difference between the two is that with LGPLv3, the crate can be used as a library without modifications in a product that uses a different license.  With GPLv3, if the crate is used as a library even without modifications, the product must have a GPLv3 compatible license.

Do you have a strong opinion about weak (MIT, BSD) and strong licenses (GPL)?

**Comment by sbillig** [comment]
AGPLv3? https://www.gnu.org/licenses/why-affero-gpl.html

**Comment by adria0** [comment]
> AGPLv3? https://www.gnu.org/licenses/why-affero-gpl.html

@sbillig finally, we decided for AGPLv3 with steroids (see LICENSE)
