### ISSUE TITLE
Add goodbye in sync boxstream

### ISSUE THREAD

**Issue by Dhole** [Kuska-ssb/kuska-handshake#16]
Depends on #15

**Comment by adria0** [comment]
`BoxStreamRecv::recv_bytes()` returning `0` could be an option, and matches with https://doc.rust-lang.org/std/io/trait.Read.html spec.

Another thing is how `{aync_std,std}::io::Read` user is aware if the connection has been properly closed or not. What about `Read` returning an `Err(std::io::Error{ kind :: UnexpectedEof })` if underlying reader returns zero and no full goodbye has been received yet?

**Comment by adria0** [comment]
partially implemented in https://github.com/adria0/ssb-study/blob/48980aa3bdd4cc9fe181187f15df4d3de7966fc4/code/src/boxstream.rs#L124

**Comment by Dhole** [comment]
> > `BoxStreamRecv::recv_bytes()` returning `0` could be an option, and matches with https://doc.rust-lang.org/std/io/trait.Read.html spec.
> 
> ^^ this currently works since goodbye is an all-zero header

Great!  So the first time a goodbye is read, a read of 0 bytes will happen and the caller can realize that it's EOF.  We need to make sure doing a write of a 0 byte length buffer doesn't send anything, to avoid sending an unexpected goodbye.

> Another thing is how `{aync_std,std}::io::Read` user is aware if the connection has been properly closed or not. What about `Read` returning an `Err(std::io::Error{ kind :: UnexpectedEof })` if underlying reader returns zero and no full goodbye has been received yet?

Sounds great to me!

**Comment by Dhole** [comment]
> > Another thing is how `{aync_std,std}::io::Read` user is aware if the connection has been properly closed or not. What about `Read` returning an `Err(std::io::Error{ kind :: UnexpectedEof })` if underlying reader returns zero and no full goodbye has been received yet?

Since we are using Read::read_all, we already have this behavior for free :)
From https://doc.rust-lang.org/std/io/trait.Read.html#method.read_exact
> If this function encounters an "end of file" before completely filling the buffer, it returns an error of the kind ErrorKind::UnexpectedEof. The contents of buf are unspecified in this case.
