### ISSUE TITLE
Reorganize repository towards a library/crate

### ISSUE THREAD

**Issue by Dhole** [Kuska-ssb/kuska-handshake#3]
This repository was initially created as a gathering of resources and study of the ssb, but it already contains a library in the `code` folder with working and somehow tested modules.

We should reorganize the entire repository so that it can be offered as a rust crate, also renaming to stop using the ssb-study name.  In case we need a space to discuss and study further stuff, we may create another repository.

It's open to debate whether to make a single crate out of this, or offer multiple crates.

**Comment by adria0** [comment]
Quick & dirty thoughts 

- crate lib  for handshake and boxstream with default for `async_std` but support for `no_std` via crate feature. In its own repo. Temporal name: habo (HAndshake & BOxstream) 

- repo for all ssbish stuff using `async_std`, with many crates, one for libs and the another ones for the execs. Temporal name: safareig

About how to manage the abstraction of crypto stuff, we can create an specific trait  and provide a base implementation, but let's open to others. Maybe we could also open this trait to be user in the other ssb modules but it could be insuficient in some cases (like paral.lel signatures verification with dalek like here). 

starting proposal

- git /xxx/habo
  - crate habo
     - agnòstic code with crypto trait
     - feature async_std (default?)
     - feature no_std
     - oxidiumize crypto impl
- git /xxx/safareig
  - crate safareig (async_std, uses habo crypto) 
    - rpc
    - rpcmux
    - secret box
    - message creation and verification
    - ... 
  - crate ssb-cli (use safareig+habo) 
  - crate bot (use safareig+habo) 
  -...

**Comment by Dhole** [comment]
>     * crate lib  for handshake and boxstream with default for `async_std` but support for `no_std` via crate feature. In its own repo. Temporal name: habo (HAndshake & BOxstream)

I like the idea of managing the no_std, and sync/async implementations via crate features!  Specially considering that the user of the library probably will only use one option out of no_std, sync, async.

I also like the idea of having the implementation of handshake and boxstream in the same crate, since they usually are used together.  Nevertheless, I want to make sure that there are no use cases where one might use handshake without boxstream or the other way around.  But anyway, we can start by having them together and if necessary splitting them in the future.

>     * repo for all ssbish stuff using `async_std`, with many crates, one for libs and the another ones for the execs. Temporal name: safareig

I understand that you imply that we will only offer an async version of the rest of the ssb modules outside of handshake and boxstream.  Maybe I would like to have a muxrpc implementation that is agnostic to allow having a sync/async version, but for the rest I think having only the async option is a good way to go.  But I'm ok if we start with an async only muxrpc.

I'm not convinced with the name because I don't know how to pronounce it in English :confused:

> About how to manage the abstraction of crypto stuff, we can create an specific trait and provide a base implementation, but let's open to others. Maybe we could also open this trait to be user in the other ssb modules but it could be insuficient in some cases (like paral.lel signatures verification with dalek like here).

This is interesting.  Using a trait would allow anyone to import the library and choose any implementation.  But we need to be careful because it could also complicate the API, making the user of the library specify the crypto implementation in many functions.  Before making a decision I would try to write down how the API would look like with this approach.

I don't see the problem with parallel signature verification.  The trait could have a blanket implementation that just calls the signature verification in serial; allowing the implementation to replace it with a true parallel verification.

> starting proposal
> 
>     * git /xxx/habo
>       
>       * crate habo
>         
>         * agnòstic code with crypto trait
>         * feature async_std (default?)
>         * feature no_std
>         * oxidiumize crypto impl
> 
>     * git /xxx/safareig
>       
>       * crate safareig (async_std, uses habo crypto)
>         
>         * rpc
>         * rpcmux
>         * secret box
>         * message creation and verification
>         * ...
>       * crate ssb-cli (use safareig+habo)
>       * crate bot (use safareig+habo)
>         -...

I would split the crates into different repositories.
- repo crypto
  - define crypto trait
  - default implementation of the crypto trait (enabled via feature crate, so that anyone can just import the crate just for the trait and do their own implementation).  I would like to try to make this default implementation `no_std`.
- repo habo
- repo "safareig"

Regarding the features of "habo", I would have only two features that are not mutually exclusive:
- `sync`
- `async`
If no features are enabled, only the agnostic part would be exposed and the crate would be `no_std`.  If any of the `sync` or `async` features are enabled, the crate is no longer `no_std`.  The reasoning behind this is that all combinations of features are valid.  If we have a feature `no_std` and a feature `async`, there would be an error if they are enabled at the same time.

I like the "safareig" organization of modules and subcrates.  Also, maybe in the future some parts of safareig can be moved to a specific repository?  But for now I think it's a good way to start.

**Comment by adria0** [comment]
"safareig" was something just to put a name, but just checking if any subexpression exists, I just found `safa` (https://www.urbandictionary.com/define.php?term=Safa) that, ok, it seems a really nice name.

:+1: with all your comments. I'm de-assigned from #7  if you want to assign to yourself, curious to see how it looks like :)

I would like to start a new branch to reorganize the repos (mainly to also add #19) but maybe is time to create a new org (or ask to join to https://github.com/ssbc/?) in order to start a new branch (from #17) to create the basic structure, it makes no sense for me to do a reorg if we need different crates/repos.
