### ISSUE TITLE
Check if we have unused libraries, and remove them if necessary

### ISSUE THREAD

**Issue by Dhole** [Kuska-ssb/kuska-handshake#33]
In https://github.com/Kuska-ssb/kuska-handshake/pull/22 mentions that he updated `Cargo.toml` to use the last version of each library, but he hasn't checked if there are any libraries that are not used.  We need to check them and remove any library that is not used.

Edit: I think `arrayref` is not currently used.  But we need to check it.

**Comment by adria0** [comment]
All libraries in `[dependencies]` are used.
- about `arrayref` : is currently used in https://github.com/Kuska-ssb/kuska-handshake/blob/17a33c0b2d62bef58e9eb0ae2c5b8b32f608e9c5/src/boxstream.rs#L68

@Dhole, I'll wait #31 to clean up the `[dev-dependencies]`, do you want to clean the old examples, I can do it also.
