### ISSUE TITLE
Do not allow builds without rustfmt

### ISSUE THREAD

**Issue by adria0** [Kuska-ssb/kuska-handshake#52]
@Dhole, with the same spirit than #48  `Do notallow builds with warnings`, what about checking in CI that all code has been formatted with rustfmt?

**Comment by Dhole** [comment]
I like this.  It will avoid cases where someone has the editor configured to auto `rustfmt` on save and just to change a single line, `rustmt` changes many other lines leading to a big commit.  Also it will force the code to look more uniform.  There is also the possibility to parametrize how `rustfmt` works with a config file (and maybe macros?)

**Comment by adria0** [comment]
Not tested, but it seems that yes, https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
